language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: fTRKyung1uWciWfc8t1vENb3S+WwCuAIKt1zvi6srMCAT00ojUf0Vkyu68pBLSJlfhEyYyY9TiLSGwyqMCpzqi8Z9OgbdjEz/RtMlFXrzSMrYYLGrU3Nbj3RV4KT4rQFd0J+dP9sqz3svNHUGvmh5pOMgGu7EDDvAHTSk7C95fZmY1HMzDCaswxTG0eycMGwoBpgJ7M6FWSsICgnkPRiggy85xAZ/BqAuOJSu+uj0rGyl5P3O2Jx0vAz5fW3unELWbprammtB7xOlDx58h2wrcSOnJwG9s2bjKQFvzwVb4QYZswi7SnNTjfu6in1+2QpkSvr58+oDUToA6mIikzqVhIC5MvYjX9tod+29xX9dO0gCB9T1AoYHRPVBAgQJlG6g+Ty1coUG3M7ZhXJqVXs3IkTreRH0hKAjbiD26D/Fz/B7PuKRu9L02Jhy9kSVBuWGJwvrUaTXo1yjubREoFEuSweiiN3H+ptAAAev47cAJUXuY33dtjK9XYzHdzMAEQ/cINnbSMH6XMMRvMTCfvJC8H5bv/+hFWdouv7VKNTy35IV7ipjPngCPoObmIXI1/FPJOb8K+F46ZeyINW/5K+6DHuiww+/W5hddHQMuU9bM1Ly91Q0UUlbl/HJGeCzL0V1yVKIR+1firMItvHkQXjfmr9jsJYbMxklsWTgJ++k34=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
